### ISSUE TITLE
Pydantic error during LauncherEngine import

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsApplicationManager#45]
Seen on Humble miniRADI

![image](https://github.com/JdeRobot/RoboticsApplicationManager/assets/40732709/e2f72b2d-0d38-4386-9cf6-45c0504e79a7)

> root@040af27c8652:/# ./entrypoint.sh 
BASE_DIR /RoboticsAcademy
Traceback (most recent call last):
  File "//RoboticsAcademy/src/manager/manager/manager.py", line 17, in <module>
    from src.manager.manager.launcher.launcher_engine import LauncherEngine
  File "/RoboticsAcademy/src/manager/manager/launcher/launcher_engine.py", line 9, in <module>
    class LauncherEngine(BaseModel):
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 95, in __new__
    private_attributes = inspect_namespace(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 328, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `module = 'src.manager.manager.launcher'`. All model fields require a type annotation; if `module` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

**Comment by pawanw17** [comment]
Issue is likely in RoboticsAcademy

**Comment by pawanw17** [comment]
The issue is due to the latest version of Pydantic that the miniRADI installs

We don't support pydantic v 2.0.x
